#include "board_config.h"
#include "stm32g0xx_hal.h"

/* Prefer CubeMX headers to get prototypes of MX_* functions */
#include "gpio.h"
#include "usart.h"

/* If your project has main.h with SystemClock_Config, you can include it too.
   We keep a weak fallback so the build passes even if CubeMX clock config
   is not generated (e.g., in early bring-up). */
#include "dma.h"
#include "main.h"

/* Fallback when CubeMX clock configuration is missing */
__weak void SystemClock_Config(void) {}

void board_init(void)
{
    /* Initialize HAL (sets up low-level drivers and SysTick/TIM timebase) */
    HAL_Init();

    /* System clock configuration (CubeMX-generated if available) */
    SystemClock_Config();

    /* GPIO & peripheral init generated by CubeMX */
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_USART2_UART_Init();
}
